### ISSUE TITLE
Support for OV9281

### ISSUE THREAD

**Issue by ncant** [ArduCAM/ArduCAM_USB_Camera_Shield#134]
Hello,
You state in the specs that the ov9281 is supported by the USB shield. However, I can't manage to make it work:
- WithUbuntu (Jetson Nano): 
```bash
$ sudo python3 ArduCam_Py_Demo.py ../../../Config/USB2.0_UC-391_Rev.E/MIPI/OV9281/2Lane/OV9281_MIPI_2Lane_RAW8_1280x800_40fps.cfg
color mode 0
Serial: AU2S-2003-0001
Capture began, rtn_val =  0
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
Error capture image, rtn_val =  65318
```
- With Windows
-- GUI: fails with mfc100.dll not found
-- Python fails with:
```bash
Traceback (most recent call last):
  File "ArduCam_Py_Demo.py", line 9, in <module>
    from ImageConvert import *
  File "C:\Users\nce\workspace\ov9281\ArduCAM_USB_Camera_Shield-master\Windows\Python\Streaming_demo\ImageConvert.py", line 2, in <module>
    import ArducamSDK
ImportError: DLL load failed while importing ArducamSDK: %1 is not a valid Win32 application.
```

Do you have an idea? The documentation is a bit sparse...
Thanks

**Comment by ncant** [comment]
OK, after some playing around I could make it work on both Windows and the Jetson:
- Wrong version of visual studio
- Use the MIPI 1 lane config file instead of the 2 lane.

Additional question: do you plan on porting the drivers of the OV9281 for the Jetson Nano? We would be very interested in connecting the camera directly on the MIPI without using the USB shield.
